
  CREATE TABLE "USER_DEMO" 
   (	"SEQ_NO" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_SIGN_UP_DATE" DATE, 
	"USER_PHONE" VARCHAR2(12 BYTE), 
	"USER_GENDER" VARCHAR2(1 BYTE), 
	"USER_SPORTS" VARCHAR2(20 BYTE), 
	"USER_COUNTRY" VARCHAR2(2 BYTE), 
	"CREATOR" VARCHAR2(20 BYTE), 
	"CREATE_DATE" DATE, 
	"MODIFIER" VARCHAR2(20 BYTE), 
	"MODIFY_DATE" DATE, 
	 CONSTRAINT "USER_DEMO_PK" PRIMARY KEY ("SEQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "USER_DEMO"."SEQ_NO" IS 'PK';
   COMMENT ON COLUMN "USER_DEMO"."USER_NAME" IS '名稱';
   COMMENT ON COLUMN "USER_DEMO"."USER_EMAIL" IS '信箱';
   COMMENT ON COLUMN "USER_DEMO"."USER_SIGN_UP_DATE" IS '註冊日期';
   COMMENT ON COLUMN "USER_DEMO"."USER_PHONE" IS '行動電話';
   COMMENT ON COLUMN "USER_DEMO"."USER_GENDER" IS '性別';
   COMMENT ON COLUMN "USER_DEMO"."USER_SPORTS" IS '運動';
   COMMENT ON COLUMN "USER_DEMO"."USER_COUNTRY" IS '國家';
   COMMENT ON COLUMN "USER_DEMO"."CREATOR" IS '建立者';
   COMMENT ON COLUMN "USER_DEMO"."CREATE_DATE" IS '建立日期';
   COMMENT ON COLUMN "USER_DEMO"."MODIFIER" IS '修改者';
   COMMENT ON COLUMN "USER_DEMO"."MODIFY_DATE" IS '修改日期';
